### ISSUE TITLE
Dado 6 facce

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#1]
Lancia un dado N_LANCI volte e conta le occorrenze delle facce

**Comment by ClaudioTazza** [comment]
Aiutino.

**Comment by ClaudioTazza** [comment]
Mi dica lei se funziona.

**Comment by FabioZTessitore** [comment]
Devi fare degli aggiustamenti
- i nomi delle funzioni del modulo dado dovrebbero essere scritti al contrario (dado_init e non init_dado ecc)
- un dado ha sei facce, l'estrazione non è corretta
- dopo aver aggiustato l'estrazione attenzione a come usi il numero estratto nel main
- devi iniziare ad usare cmake

**Comment by ClaudioTazza** [comment]
non mi piace cmake :c 
a malapena riesco a usare il c dopo tempo :C 
Rimandiamo.. :D

**Comment by FabioZTessitore** [comment]
Devi fare degli aggiustamenti
- i nomi delle funzioni del modulo dado dovrebbero essere scritti al contrario (dado_init e non init_dado ecc)
- devi iniziare ad usare cmake
- devi stampare la percentuale ottenuta e quella teorica

**Comment by FabioZTessitore** [comment]
Devi fare degli aggiustamenti
- ripulire la directory
- devi iniziare ad usare cmake
- devi stampare la percentuale ottenuta e quella teorica

**Comment by ClaudioTazza** [comment]
un po' meglio?

**Comment by FabioZTessitore** [comment]
Devi fare degli aggiustamenti
- aggiungere .gitignore così non si sporca più (non solo a te, ma neanche a me quando provo i codici)
- devi iniziare ad usare cmake
- devi stampare la percentuale teorica

**Comment by ClaudioTazza** [comment]
devo scrivere 15,33333333333333333333333333333333333333? <.<

**Comment by FabioZTessitore** [comment]
maledetto

**Comment by ClaudioTazza** [comment]
Davvero, non ho capito xD

**Comment by FabioZTessitore** [comment]
quante sono le probabilità che lanciando un dado esca 1?
e quante quelle che esca 2? e così via.
In realtà questi sei eventi sono equiprobabili quindi basta calcolarne uno e stamparlo

**Comment by ClaudioTazza** [comment]
Like this?

**Comment by FabioZTessitore** [comment]
ok, solo per la cronaca dovresti usare più cifre significative (sia nella tabella che nel valore teorico)

resta da utilizzare cmake. comincia con random

**Comment by ClaudioTazza** [comment]
Devo proprio? T.T 
Non possiamo aspettare che lei capisca meglio tutte le sue funzionalità? :D

**Comment by FabioZTessitore** [comment]
forza forza

**Comment by ClaudioTazza** [comment]
Deve inviami la documentazione. 
Non ricordo come scrivere le cose.

**Comment by FabioZTessitore** [comment]
Prima di tutto crea una directory `random`, mettici dentro i file `random.h` e `random.c`. Aggiungi poi un file `CMakeLists.txt`.
Fai la stessa cosa con `dado`

**Comment by FabioZTessitore** [comment]
### `random/CmakeLists.txt`

contiene sono
`add_library (Random random.c random.h)`

**Comment by FabioZTessitore** [comment]
### dado/CMakeLists.txt

passiamo a dado

anche qui serve una riga come quella di prima
`add_library (Dado dado.c dado.h)`

però non basta perché il modulo dado dipende dal modulo random. Quindi devi aggiungere
`target_link_libraries (Dado Random)`

Infine, per far funzionare `#include "random.h"` (ora random.h non si trova nella stessa directory di dado.c e dado.h)
`include_directories (../random)`

Ricapitolando

```
include_directories (../random)

add_library (Dado dado.c dado.h)
target_link_libraries (Dado Random)
```

**Comment by ClaudioTazza** [comment]
Done

**Comment by FabioZTessitore** [comment]
rispetta l'ordine con cui ho scritto le righe.
Prima si mettono le configurazioni, in questo caso diciamo che vogliamo includere file presenti in ../random e alla fine diciamo cosa vogliamo costruire

**Comment by ClaudioTazza** [comment]
Avevo fatto secondo l'ordine della spiegazione.

**Comment by FabioZTessitore** [comment]
ma avevo ricapitolato alla fine ... cmq andiamo avanti

ora crea un altro file CMakeLists.txt nella cartella principale del progetto, dove c'è il main

**Comment by ClaudioTazza** [comment]
did it.

**Comment by FabioZTessitore** [comment]
questo è il file principale da cui tutti gli altri dipendono.
Per prima cosa bisogna dire che abbiamo bisogno di una qualunque versione di cmake purché successiva ad una di base. Negli esempi ho sempre trovato la 2.6
`cmake_minimum_required (VERSION 2.6)`

poi diamo un nome la progetto
`project (LanciaDado)`

diciamo che vogliamo includere i file presenti in dado/ (lo facciamo nel main)
`include_directories (dado)`

a questo punto diamo indicazioni sulle directory del progetto
`add_subdirectory (random)`
`add_subdirectory (dado)`

infine in maniera equivalente a quanto visto prima in dado creiamo l'eseguibile e aggiungiamo le librerie
`add_executable (LanciaDado main.c)`
`target_link_libraries (LanciaDado Dado)`

**Comment by ClaudioTazza** [comment]
Ok

**Comment by FabioZTessitore** [comment]
ok ci siamo
devi solo correggere un errore di battitura in dado/CMakeLists.txt (non hai scritto bene library)

per compilare
crea la cartella build
entra in build e lancia `cmake ..` (attento al doppio punto)
e poi `make`
dovresti avere il tuo eseguibile

have fun

**Comment by ClaudioTazza** [comment]
http://zty.pe/

Lo provi, semplice, sfizioso, efficace.

2016-11-07 19:00 GMT+01:00 Fabio Z Tessitore notifications@github.com:
