### ISSUE TITLE
Prodotto Scalare

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#10]
Have fun

**Comment by ClaudioTazza** [comment]
Va bene?

**Comment by FabioZTessitore** [comment]
la smetti di caricare cose inutili, a che serve build?

nel main.c a che serve i?

**Comment by ClaudioTazza** [comment]
build non volevo caricarlo :/
dopo averlo cancellato non ho ripetuto "git add ."
Per la i invece, all'inizio credevo di dover fare l'ennesimo ciclo e poi mi
sono dimenticato di eliminarla hehe

2016-11-19 19:12 GMT+01:00 Fabio Z Tessitore notifications@github.com:
