### ISSUE TITLE
Ordinamento Vettori

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#11]
Il metodo piu' semplice (e meno efficiente) per
riordinare gli elementi di un vettore e' il
cosiddetto bubble sort o ordinamento a bolle.
L'algoritmo consiste nello scorrere gli elementi del vettore
e se l'elemento corrente risulta maggiore del successivo
vengono invertite le loro posizioni.
Alla fine del primo passaggio l'elemento maggiore sara' in fondo.
Il procedimento viene ripetuto fino ad ottenere
l'ordinamento di tutto il vettore.

**Comment by FabioZTessitore** [comment]
![es6_11](https://cloud.githubusercontent.com/assets/3002194/20457528/e59a9fde-ae8d-11e6-8bd5-a10fa7c6f6e2.png)

**Comment by ClaudioTazza** [comment]
La prossima volta mandate un solo messaggio per la issue T.T
Ho praticamente fatto l'esercizio che mi avete mandato T.T

**Comment by FabioZTessitore** [comment]
ma non ti arrivano le notifiche quando scrivo qualcosa?

**Comment by ClaudioTazza** [comment]
solo se guardo il sito T.T

**Comment by FabioZTessitore** [comment]
dovrebbe arrivarti una mail (se non hai disattivato)

**Comment by ClaudioTazza** [comment]
almeno è fatto decentemente il mio lavoro 'sprecato' T.T

**Comment by ClaudioTazza** [comment]
l'ho disattivato... hehe

**Comment by FabioZTessitore** [comment]
ovviamente no. A parte i nomi delle variabili incomprensibili e il fatto che non hai creato un modulo myvect_sort ... l'algoritmo non è corretto. Il bubble sort funziona in un altro modo: si fanno un certo numero di passaggi sul vettore e per ogni passaggio si controlla se ci sono elementi adiacenti non in ordine

**Comment by FabioZTessitore** [comment]
controllore ok
riguardo a size credevo di averti già detto che non è una buona idea modificare il valore di fine ciclo perché uno legge e si aspetta una cosa, invece poi il valore cambia

**Comment by ClaudioTazza** [comment]
deve diminuire dato che non c'è più bisogno che arrivi fino alla fine. 
Se me lo dice lei prometto di non dimenticare l'insegnamento

**Comment by FabioZTessitore** [comment]
Una cosa è far diminuire il termine nella condizione del ciclo e una cosa è far diminuire il valore di size (che dovrebbe essere costante)

**Comment by ClaudioTazza** [comment]
Va meglio?

**Comment by FabioZTessitore** [comment]
certo che no, ha solo cambiato nome

**Comment by ClaudioTazza** [comment]
Ma size è rimasta una costante.

**Comment by FabioZTessitore** [comment]
ripeto:
Una cosa è far diminuire il termine nella condizione del ciclo e una cosa è far diminuire il valore di size (che dovrebbe essere costante)

**Comment by ClaudioTazza** [comment]
..così?

**Comment by FabioZTessitore** [comment]
ci stiamo avvicinando
ora dovresti renderti conto che non hai bisogno di questa nuova variabile perché i valori che ti servono li hai già da qualche altra parte

**Comment by ClaudioTazza** [comment]
:D

**Comment by FabioZTessitore** [comment]
ok, trasferisci la funzione in un modulo myvect_sort
