### ISSUE TITLE
selection sort

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#12]
![es6_32](https://cloud.githubusercontent.com/assets/3002194/20498155/4928b6fe-b02c-11e6-8b34-e7099bcd6288.png)

**Comment by ClaudioTazza** [comment]
Per che cosa sta **sort**?

**Comment by FabioZTessitore** [comment]
to sort = ordinare

**Comment by ClaudioTazza** [comment]
Ps L'esercizio per come è scritto non mi risulta chiarissimo.
Cosa si intende per **sottovettore**?

**Comment by FabioZTessitore** [comment]
parte del vettore

**Comment by ClaudioTazza** [comment]
Se ho capito:
La funzione deve capire guardando tutti gli elementi del vettore chi è il più piccolo e metterlo nella cella 0;
Dopo aver fatto ciò deve rifare lo stesso controllo senza però contare la cella 0 che abbiamo stabilito contenere già l'elemento più piccolo;

**Comment by FabioZTessitore** [comment]
si

**Comment by ClaudioTazza** [comment]
Però ricorsiva.

**Comment by FabioZTessitore** [comment]
esatto, ma la ricorsione ti semplificherà il lavoro

**Comment by ClaudioTazza** [comment]
Questa funzione ordina un vettore, così come ordinava il vettore anche la funzione precendente (anche se in modo diverso); Ha senso conservarle entrambe? Oppure la funzione creata nella issue precedente la mettiamo nel dimenticatoio?

**Comment by FabioZTessitore** [comment]
conservale tutte nello stesso modulo myvect_sort

**Comment by ClaudioTazza** [comment]
L'ho chiesto per chiarimenti;
Se fanno la stessa cosa ma una delle 2 lo fa meglio, perchè conservarle entrambe?
Se avessi bisogno di ordinare un *vettore* perchè dovrei scegliere di utilizzare la funzione che lavora nel modo peggiore? :/

**Comment by FabioZTessitore** [comment]
meglio e peggio sono cose relative

**Comment by ClaudioTazza** [comment]
Non mi faccia male..
Almeno funziona :D

**Comment by FabioZTessitore** [comment]
Sig Tazza, ma cosa mi combina?

**Comment by ClaudioTazza** [comment]
Aspetto che lei mi dia una pista T.T

**Comment by ClaudioTazza** [comment]
Beh.. fa quello che deve fare.. è ricorsiva.. :D

**Comment by FabioZTessitore** [comment]
e cosa mi dice di quel ciclo?

**Comment by ClaudioTazza** [comment]
Speravo funzionasse.

**Comment by FabioZTessitore** [comment]
ci stiamo avvicinando ... ma ancora non va bene. Il codice è inutilmente complesso.

L'algoritmo spiega che vanno fatti due passi:
1) ricerca del minimo
2) eventuale scambio

**Comment by ClaudioTazza** [comment]
C'è bisogno della variabile **conta** o è un più?

**Comment by FabioZTessitore** [comment]
immagino tu conosca già la risposta

**Comment by ClaudioTazza** [comment]
Lei non se ne rende conto, ma con queste risposte mi manda un pericoloso stato di paranoia e incertezza.
Se mai uno psicologo dovesse chiamarla per informazioni su un suo cliente, non si stupisca.

**Comment by FabioZTessitore** [comment]
haha, devi imparare a leggere la traccia del problema (magari capirla)

**Comment by ClaudioTazza** [comment]
if(vettore[celltostart] > vettore[celltostart + conta])
  vsort_ordinaMeglio(vettore, n_elem, celltostart, conta++);

else
  scambia()

if(conta == n_elem)
  vsort_ordinaMelgio(vettore, n_elem, celltostart++, 1)

È così che lo farei

**Comment by FabioZTessitore** [comment]
sono algoritmi standard, non puoi farlo a piacere tuo. Segui la traccia
