### ISSUE TITLE
ricerche

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#13]
ho caricato ricerca lineare e binaria
dai un'occhiata e vedi se qualcosa non ti è chiaro

**Comment by ClaudioTazza** [comment]
È molto più semplice la ricerca lineare.
Perchè si dovrebbe utilizzare la ricerca binaria?
(Contando che c'è anche bisogno che il vettore sia ordinato per utilizzare la ricerca binaria)

**Comment by FabioZTessitore** [comment]
questa la mettiamo nel libro

la ricerca binaria è molto più veloce (ricordi guess e come facevi per indovinare il numero?)
quindi se devi fare molte ricerche è meglio perdere un po' di tempo una volta per fare l'ordinamento e poi fare ricerche molto più rapide

**Comment by ClaudioTazza** [comment]
Chiaro
