### ISSUE TITLE
duplicati

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#14]
![es6_15](https://cloud.githubusercontent.com/assets/3002194/20648773/f9e19010-b4af-11e6-83f1-3c38284ad9c3.png)

**Comment by FabioZTessitore** [comment]
come puoi dire che funziona?

**Comment by ClaudioTazza** [comment]
![problema](https://cloud.githubusercontent.com/assets/16176113/20734059/4df34f0c-b697-11e6-849c-da497214e21f.png)

**Comment by ClaudioTazza** [comment]
"Visualizzarlo qualora non sia un duplicato di uno già letto"
Io sono un po' tonto e vabè; 
Ma forse detto con altre parole potrebbe essere più chiaro

**Comment by FabioZTessitore** [comment]
tu come lo avresti detto?

**Comment by ClaudioTazza** [comment]
Ogni volta che si legge un numero, se non inserito precedentemente, visualizzarlo; Altrimenti ignorare la sua misera esistenza dato che uno come lui è già arrivato prima e gli ha fregato il posto.
