### ISSUE TITLE
passaggio di matrici a funzioni

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#16]
vedi prima questo

dovrai usare le funzioni, mica vuoi fare tutto nel main!

**Comment by ClaudioTazza** [comment]
Ho tante domande

**Comment by ClaudioTazza** [comment]
void init_matrice(int m[][NCOLS], int rows, int cols);

A cosa serve effettivamente quel **NCOLS**?
Se gli passo una matrice con 31 colonne non l'accetta?

**Comment by FabioZTessitore** [comment]
le funzioni che accettano matrici sono schizzinose, devi specificare quante colonne ha la matrice e non accettano matrici con numero di colonne diverso

il trucco (per iniziare) sta nel dichiarare una matrice "abbastanza grande" da andare bene per tutti gli scopi, poi puoi usarne solo una parte specificando righe e colonne effettivamente utilizzate

**Comment by ClaudioTazza** [comment]
Mi sembra abbastanza fastidioso..

**Comment by ClaudioTazza** [comment]
Ok chiaro
