### ISSUE TITLE
bucket sort

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#17]
![es6_31](https://cloud.githubusercontent.com/assets/3002194/20761686/0dc6e9a6-b724-11e6-9e24-c2f2c8505f70.png)

**Comment by FabioZTessitore** [comment]
a che stai?

**Comment by ClaudioTazza** [comment]
a 38,3 hehe
Mi deve scusare per la mia assenza in questi giorni, ma sono ancora ammalato.
Per le previsioni di mio padre dovrei riprendermi per venerdi'

**Comment by ClaudioTazza** [comment]
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/lucifero/Scrivania/vettori/bucket_sort/build/CMakeFiles/CMakeOutput.log".
See also "/home/lucifero/Scrivania/vettori/bucket_sort/build/CMakeFiles/CMakeError.log".

**Comment by ClaudioTazza** [comment]
errore che esce dopo aver lanciato "cmake .."

**Comment by FabioZTessitore** [comment]
Per qualche ragione crede di dover usare il compilatore c++
Che stai combinando?

Il 21 dic 2016 9:35 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/lucifero/Scrivania/vettori/dado/build/CMakeFiles/CMakeOutput.log".
See also "/home/lucifero/Scrivania/vettori/dado/build/CMakeFiles/CMakeError.log".


Questo esce provando provo a compilare dado.

**Comment by FabioZTessitore** [comment]
Prova a cancellare build e riprova

Il 21 dic 2016 9:40 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Non funziona.
Provo installando gcc-c++

**Comment by ClaudioTazza** [comment]
Adesso funziona.

**Comment by FabioZTessitore** [comment]
Ma lo stai accontentando ...

Il 21 dic 2016 9:45 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Se si mette a fare il bambino tanto vale dargli quello che vuole

**Comment by ClaudioTazza** [comment]
la funzione mi verrebbe da crearla con 9 if e un else

**Comment by ClaudioTazza** [comment]
Ok risolto

**Comment by ClaudioTazza** [comment]
va bene così?

**Comment by FabioZTessitore** [comment]
non so da dove cominciare, non ce la faccio

**Comment by ClaudioTazza** [comment]
Un viaggio mi 1'000 kilometri comincia sempre con un primo passo

**Comment by FabioZTessitore** [comment]
cominciamo dalla matrice. La matrice **non** deve comparire nel codice. Se ho un vettore da ordinare **non** devo sapere come la funzione bucket_sort() fa questo ordinamento.

**Comment by FabioZTessitore** [comment]
Mi sembra un buon punto di partenza.
Continua

**Comment by ClaudioTazza** [comment]
Come si fa a settare tutti i valori di una matrice a 0?

**Comment by FabioZTessitore** [comment]
Non ne hai bisogno e sarebbe sbagliato. Potrebbero esserci degli zero nel
vettore da riordinare

Il 2 gen 2017 5:47 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Quindi il codice e' del tutto fuori strada?

**Comment by FabioZTessitore** [comment]
È un punto di partenza, ovviamente farlocco.
Non va bene usare lo zero come indicatore della.posizione, bisogna trovare un'altra strategia

**Comment by ClaudioTazza** [comment]
I valori non impostati da noi in una matrice sono casuali?

**Comment by FabioZTessitore** [comment]
Certo, come tutte le variabili. Il problema è che qualunque numero potrebbe essere presente nel vettore da ordinare

**Comment by ClaudioTazza** [comment]
Se ci fosse una numero casuale che casualmente ha la stessa unita' della sua riga, come potrei fare per capire che non faceva parte del vettore?

**Comment by FabioZTessitore** [comment]
Questo è il problema che devi risolvere

**Comment by ClaudioTazza** [comment]
Si puo' fare una cosa tipo Vettore[size] = Vettore2[size]
In modo che venga cancellato il contenuto di **Vettore** e sostituito con il contenuto di  **Vettore2**?

**Comment by FabioZTessitore** [comment]
dopo aver messo i valori nella matrice, prova a stamparla (però solo i valori presenti nel vettore!)
le righe da 76 in poi neanche le guardo

**Comment by ClaudioTazza** [comment]
Questo che ho provato a fare e':
  prendere il primo elemento della matrice
  controllare se presente dentro al vettore
  se presente lo mette in un vettore chiamato **vor** (vettore ordinato)
  passare al prossimo elemento della matrice

  infine sostituire il vettore ordinato con il vettore da ordinare

**Comment by FabioZTessitore** [comment]
Bocciato

**Comment by ClaudioTazza** [comment]
lei e' una persona cattiva

**Comment by FabioZTessitore** [comment]
tra poco verrà retrocesso.
provi a fare tutto il procedimento, così come descritto, a mano

**Comment by ClaudioTazza** [comment]
nel secondo passaggio non ho capito come far capire al sistema come individuare i valori giusti della matrice.

**Comment by ClaudioTazza** [comment]
il problema sta nella randomicita' dei valori della matrice.

**Comment by FabioZTessitore** [comment]
il problema sta nel fatto che non riesce a trovare una soluzione al problema

**Comment by ClaudioTazza** [comment]
se su carta avessi un vettore e una matrice con al suo interno oltre a valori casuali, anche gli stessi valori del vettore, sarebbe facile capire quali sono, perchè si vedono le corrispondenze.

E quindi farei un programma che contronta i due alla ricerca dei valori simili.

**Comment by FabioZTessitore** [comment]
E abbiamo già scartato questa strada

**Comment by ClaudioTazza** [comment]
Si potrebbe provare scartando tutti i numeri che non hanno l'unità che corrisponde alla riga dove si trovano, ma parlando di numeri randomici, si potrebbero creare degli errori di selezione.

**Comment by FabioZTessitore** [comment]
Io vorrei sapere perché le soluzioni semplici non le vedi mai

**Comment by ClaudioTazza** [comment]
potrei mettere un terminatore la cella successiva a quella utilizzata?
così da capire quando fermarmi

**Comment by ClaudioTazza** [comment]
Lo vorrei sapere anche io

**Comment by FabioZTessitore** [comment]
Sono interi, qualunque terminatore si confonderà con gli altri

**Comment by ClaudioTazza** [comment]
![img_0780](https://cloud.githubusercontent.com/assets/16176113/21615284/25c38662-d1dd-11e6-830f-0bc4ed72df05.JPG)

**Comment by ClaudioTazza** [comment]
Non mi ero accorto che era sbagliato anche il modo in cui inserisco i numeri nella matrice

**Comment by FabioZTessitore** [comment]
Ok. Ora devi trovare la soluzione al problema "quanti elementi in una riga"

**Comment by ClaudioTazza** [comment]
in una riga possono stare massimo 4 elementi se il vettore e' di 4 elementi

**Comment by FabioZTessitore** [comment]
Si ma quanti ce ne sono effettivamente?

**Comment by ClaudioTazza** [comment]
nel disegno ci sono 3 elementi possibili in una riga

**Comment by FabioZTessitore** [comment]
Non è questione di possibili, ma di quanti ce ne sono. Dalla matrice bisogna passare al vettore

**Comment by ClaudioTazza** [comment]
ce ne sono 2

**Comment by FabioZTessitore** [comment]
In una riga. E nelle altre? Cmq riesci a saperlo solo perché fai un qualche ragionamento. Ma quale?

**Comment by ClaudioTazza** [comment]
quando metto una variabile nella riga 1, devo segnarlo in una variabile che se ne ricordi?

**Comment by FabioZTessitore** [comment]
Fuochino

**Comment by ClaudioTazza** [comment]
nelle altre righe 1 o nessun valore. Semplicemente li conto

**Comment by FabioZTessitore** [comment]
Che significa?

**Comment by ClaudioTazza** [comment]
![15871297_10205958928571581_1525547349_n](https://cloud.githubusercontent.com/assets/16176113/21621945/97bd333a-d1fb-11e6-9c4b-abaaea26f884.jpg)
Qualcosa del tipo?

**Comment by FabioZTessitore** [comment]
Si, qualcosa del tipo

Ps. Ti sei fatto la lavagna?

**Comment by ClaudioTazza** [comment]
Si :3 
Comodissima :3

**Comment by FabioZTessitore** [comment]
È bellissima!

**Comment by FabioZTessitore** [comment]
la dimensione di conta[]?

**Comment by ClaudioTazza** [comment]
size

**Comment by ClaudioTazza** [comment]
cioe' dovrebbe essere 10 hehe. Errore mio

**Comment by FabioZTessitore** [comment]
avevo letto ... ti sembra corretto?

**Comment by FabioZTessitore** [comment]
ok

**Comment by FabioZTessitore** [comment]
vai avanti, cerca di implementare tutto l'algoritmo ora

**Comment by FabioZTessitore** [comment]
stessa cosa

**Comment by ClaudioTazza** [comment]
Pare funzionare

**Comment by FabioZTessitore** [comment]
ammesso che funzioni, fai un solo passaggio. Alla fine non è detto che il vettore sia ordinato

**Comment by ClaudioTazza** [comment]
Ok funziona, ma in maniera molto farlocca

**Comment by FabioZTessitore** [comment]
è più farlocca di quello che potessi immaginare

**Comment by ClaudioTazza** [comment]
Per quanto la sintassi possa non essere il massimo, funziona come si deve.

**Comment by FabioZTessitore** [comment]
ma va?
funziona pure se metti il vettore
2000 1030

**Comment by ClaudioTazza** [comment]
Quello era solo per vedere se funzionava anche con numeri di diverse dimensioni

**Comment by FabioZTessitore** [comment]
ah, ho capito

ora quanto tempo ci vorrà per farlo funzionare e basta?

**Comment by ClaudioTazza** [comment]
Funziona gia' adesso

**Comment by FabioZTessitore** [comment]
puoi scrivere un main in cui crei un vettore di 10 interi casuali tra 0 e 1000?

**Comment by ClaudioTazza** [comment]
Did it
