### ISSUE TITLE
bucket sort

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#19]
fai un pull, ho fatto qualche piccola modifica

e leggi il commento in main

**Comment by ClaudioTazza** [comment]
risolto

**Comment by ClaudioTazza** [comment]
anche se non ho capito come possano andare 11 valori in una sola riga, di una matrice 10x10

**Comment by FabioZTessitore** [comment]
infatti non possono andarci, il fatto che la matrice sia 10x10 potrebbe essere una delle tue cose farlocche?

**Comment by ClaudioTazza** [comment]
tristezza

**Comment by FabioZTessitore** [comment]
la tristezza viene a me, aggiusti una cosa e ne rompi un'altra

ps. leggi i dialoghi

**Comment by ClaudioTazza** [comment]
Non va bene?
(Li sto leggendo)

**Comment by FabioZTessitore** [comment]
te l'ho detto, una l'hai aggiustata, l'altra l'hai rotta

**Comment by ClaudioTazza** [comment]
ma ho fatto una cosa alla volta, com'e' possibile?

**Comment by ClaudioTazza** [comment]
per fare una matrice di dimensioni giuste devo per forza guardare il valore di size. Non credo ci sia altro modo.
O se c'e' ignoro la sua esistenza

**Comment by FabioZTessitore** [comment]
una matrice ha due dimensioni

**Comment by ClaudioTazza** [comment]
Righe e colonne

**Comment by ClaudioTazza** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaahhhhh

**Comment by ClaudioTazza** [comment]
giusto

**Comment by FabioZTessitore** [comment]
sei pessimo, non ci sono parole
