### ISSUE TITLE
due dadi

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#2]
prova a fare lo stesso esercizio ma con due dadi

**Comment by ClaudioTazza** [comment]
Done

**Comment by ClaudioTazza** [comment]
Va bene?

**Comment by FabioZTessitore** [comment]
ma che hai fatto? hai raddoppiato il codice???
devi lanciare due dadi invece di uno e vedere quanto esce e se sono rispettate le probabilità teoriche

**Comment by ClaudioTazza** [comment]
Non ho capito.
Già nel primo programma chiedeva in ingresso quanti dadi lanciare.

**Comment by FabioZTessitore** [comment]
no. Chiedeva quante volte lanciare il dado.
Anche qui devi chiedere quanti lanci fare, ma i dadi da lanciare sono due alla volta

**Comment by ClaudioTazza** [comment]
Cosa dovrei stampare?

**Comment by ClaudioTazza** [comment]
uno volta mi mandava delle immagini illustrative.
Era tutto più semplice :c

**Comment by ClaudioTazza** [comment]
Le va bene se faccio fare 2 volte il ciclo presente nel primo programma?
Lo inserisco in un ciclo che ripete il tutto a seconda del volere che do a un ipotetico "num_Dadi".

**Comment by ClaudioTazza** [comment]
Voi potreste dire:"Radoppi semplicemente il numero di lanci del singolo dado".
Beh, è vero, ma farlo così o in un altro modo dara comunque lo stesso risultato essendo dadi identici.

**Comment by ClaudioTazza** [comment]
Perchè non funziona?

**Comment by FabioZTessitore** [comment]
prima di tutto ragioniamo un po' sulla libreria dado.
Prima avevi una funzione che lanciava un dado, ora hai una funzione che lancia `a` dadi.
Il problema è che la prima era comoda perché non necessitava di parametri per funzionare.
Una buona soluzione potrebbe essere quella di aggiungere una funzione `dado_lancia_n()` e lasciare inalterata la `dado_lancia()`

nel main riguardati un po' gli indici

infine rifatti i calcoli delle percentuali teoriche
