### ISSUE TITLE
reverse input

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#4]
e questo?

**Comment by ClaudioTazza** [comment]
?

**Comment by ClaudioTazza** [comment]
Se devo fare altro deve ricordarmelo.

**Comment by FabioZTessitore** [comment]
devi fare il programma che stampa in ordine inverso i dati inseriti in input

**Comment by FabioZTessitore** [comment]
ogni volta che chiedo un programma che lavora con dati generici mi fate l'input dei valori. ora che ti ho chiesto l'input dei valori, hai messo i dati
