### ISSUE TITLE
indirizzo di un vettore

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#7]
guarda indirizzo di un vettore

**Comment by ClaudioTazza** [comment]
Chiaro

**Comment by FabioZTessitore** [comment]
quindi se facciamo un passaggio di un vettore ad una funzione che tipo di passaggio è?

**Comment by ClaudioTazza** [comment]
Per indirizzo

**Comment by FabioZTessitore** [comment]
eh, si dice per riferimento
vai a vedere il codice

**Comment by ClaudioTazza** [comment]
Quando di deve ritornare un stringa bisogna fare "char *"?

**Comment by FabioZTessitore** [comment]
si perché si ritorna l'indirizzo del vettore di caratteri in realtà
