### ISSUE TITLE
inverte vettore

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Vettori#8]
ora iniziamo a costruire una libreria per lavorare con i vettori.
Chiamala myvect e usa cmake (ci servirà random, vai a cercarlo)

Nel modulo myvect metterai funzioni di uso comune quando si lavora con i vettori
myvect_init() inizializza il modulo affinché tutto funzioni correttamente
myvect_vec_in_range() inizializza un vettore (da passare come parametro) con numeri casuali compresi tra un minimo e un massimo (altri parametri)
myvect_reverse() inverte l'ordine degli elementi
myvect_print() stampa gli elementi del vettore

have fun

**Comment by FabioZTessitore** [comment]
hai provato a compilare?

ps la funzione myvect_vec_in_range deve riempire il vettore con numeri casuali, non estrarre un numero

**Comment by FabioZTessitore** [comment]
i prototipi di myvect sono errati
in main non chiami myvect_init()
nella stampa del vettore cosa significa \f?

**Comment by ClaudioTazza** [comment]
Doveva essere un t.

**Comment by FabioZTessitore** [comment]
ok, correggi le altre cose

**Comment by ClaudioTazza** [comment]
non ho capito però perchè sono sbagliati

**Comment by FabioZTessitore** [comment]
perché dai prototipi non si evince che le funzioni accettano vettori

**Comment by ClaudioTazza** [comment]
se prima non funzionava, ora non compila :D

**Comment by FabioZTessitore** [comment]
perché ovviamente non leggi le cose che ti mando ...
abbiamo capito che sai scrivere una funzione che accetta un vettore, ma come la si invoca?

**Comment by FabioZTessitore** [comment]
riprova sarai più fortunato

**Comment by ClaudioTazza** [comment]
Cosa non va?

**Comment by FabioZTessitore** [comment]
Sig Tazza, lei non sa passare un vettore ad una funzione

**Comment by ClaudioTazza** [comment]
Questo perchè avete messo passaggio per riferimento a tradimento. 
Non c'era una issue che mi chiedesse di leggerlo.
Lei è un birbone.

**Comment by FabioZTessitore** [comment]
devi fare solo alcuni piccoli aggiustamenti
1) nel main evita di usare la variabile `i` (se non vuoi usare un numero definisci una costante simbolica con `#define`
2) nei prototipi di funzione metti i nomi dei parametri così si capiscono meglio
3) metti la dimensione del vettore subito dopo il vettore nella lista dei parametri, sono chiaramente informazioni correlate

poi puoi procedere con la funzione myvect_reverse()

**Comment by ClaudioTazza** [comment]
ho fatto il 3);
il 2) ora lo faccio;
l'1) non l'ho capito, ho sempre usa i come indice, come mai ora non va più bene?

**Comment by FabioZTessitore** [comment]
perché nel main non è un indice, è la dimensione del vettore

**Comment by lucifero55** [comment]
come si clona un vettore?
Es 'vet2 = vet'

**Comment by ClaudioTazza** [comment]
Come faccio a creare un secondo vettore identico al primo?

**Comment by FabioZTessitore** [comment]
non ti serve

**Comment by ClaudioTazza** [comment]
Ecco come lo avrei fatto, ma per ovvi motivi non funziona.
Con una variabile vet2 identico a vet si risolverebbe il problema.

**Comment by FabioZTessitore** [comment]
non ti serve il vettore temp, ragiona sulle singole componenti

**Comment by ClaudioTazza** [comment]
tempo era un test che mi sono dimenticato di togliere.
Questo era quello che volevo farvi vedere.

**Comment by FabioZTessitore** [comment]
la strada è quella giusta, non capisco perché non lo provi e non correggi gli errori

**Comment by ClaudioTazza** [comment]
lo provo, ma a metà si ripete (giustamente)

**Comment by FabioZTessitore** [comment]
niente giustamente, non si deve ripetere

**Comment by ClaudioTazza** [comment]
Intendo dire, che ho capito perchè succede, ma non come fare per far si che non accada.

**Comment by FabioZTessitore** [comment]
se lo avessi capito davvero sapresti come risolvere

**Comment by ClaudioTazza** [comment]
Quando nel ciclo si arriva a metà del vettore, i valori da 0 a metà sono stati sostituiti da quelli successivi;
Quindi il loro contenuto è come cancellato.

**Comment by ClaudioTazza** [comment]
sovrascritto

**Comment by FabioZTessitore** [comment]
eh lo so bene.
Quando si inizia a programmare, proprio all'inizio, si fanno gli esercizi sulle assegnazioni e sullo scambio di valori tra variabili ...

**Comment by ClaudioTazza** [comment]
credevo ci potessero essere problemi se il numero di elementi fossero stati dispari. Scemo io hehe

**Comment by FabioZTessitore** [comment]
un'ultima cosa:
quando hai un ciclo `for (...; i < n; ...)`, modificare il valore di `n` non è una buona abitudine perché ci si aspetta che sia un numero costante e rende meno chiaro il codice

**Comment by ClaudioTazza** [comment]
Consigli?

**Comment by FabioZTessitore** [comment]
dai che è facile

**Comment by ClaudioTazza** [comment]
1)  (...; i < n-1; ...)
2)  n--  
    (...; i < n; ...)

**Comment by FabioZTessitore** [comment]
n non deve cambiare

**Comment by ClaudioTazza** [comment]
i2 = n - 1;
for( .. ;i < i2; ..)

**Comment by ClaudioTazza** [comment]
Ps Cos'è quel fork che mi ritrovo?

**Comment by ClaudioTazza** [comment]
Ok non avevo capito cosa volevate dire.

**Comment by ClaudioTazza** [comment]
Possiamo andare avanti?

**Comment by FabioZTessitore** [comment]
Ma certo. Riciclando tutto il possibile crea un programma che fa la media
degli elementi di un vettore. (Aggiungi il modulo myvect_math)

Il martedì 15 novembre 2016, lucifero55 notifications@github.com ha
scritto:

**Comment by ClaudioTazza** [comment]
Mi chiedevo, solo myvect dipende da random e il main non ne ha bisogno, quindi non sarebbe più ordinato spostare la cartella random nella cartella myvect?
(Cosi lanciando il comando 'tree' si può avere già l'idea di come funzioni il tutto)
A me sembra molto ordinato. Mi dica lei.

**Comment by FabioZTessitore** [comment]
Ci sono due problemi con il tuo approccio

Il primo è che in un programma potresti avere tanti moduli che dipendono da
random. Mica puoi mettere copie ovunque

Il secondo è che il sistema di gestione delle dipendenze non è
particolarmente raffinato (questo è il motivo per cui nel CMakeLists.txt
principale mettiamo tutte le info sui sottoprogrammi)

Il martedì 15 novembre 2016, lucifero55 notifications@github.com ha
scritto:

**Comment by ClaudioTazza** [comment]
Aggiunto la cartella

**Comment by ClaudioTazza** [comment]
Prossimo esercizio?
